"use client"

import { ChangeEvent, useEffect, useRef, useState } from "react"
import { BookOpen, ChevronLeft, ChevronRight, Download, FileText, FolderOpen, Fullscreen, Menu, Minus, MoreHorizontal, PanelLeft, Plus, Printer, RotateCw, Search, Share2, SlidersHorizontal, X } from "lucide-react"
import * as pdfjsLib from "pdfjs-dist"
import "pdfjs-dist/web/pdf_viewer.css"

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.mjs", import.meta.url).toString()
const chapters = ["Cover", "Contents", "Introduction", "Getting started", "The document view", "Keyboard shortcuts", "About this guide"]

export default function ReaderPage() {
  const [page, setPage] = useState(1), [zoom, setZoom] = useState(100), [rotation, setRotation] = useState(0)
  const [sidebar, setSidebar] = useState(true), [searchOpen, setSearchOpen] = useState(false), [mobileMenu, setMobileMenu] = useState(false), [dark, setDark] = useState(false)
  const [filename, setFilename] = useState(""), [pdf, setPdf] = useState<pdfjsLib.PDFDocumentProxy | null>(null), [tab, setTab] = useState<"outline" | "pages">("outline")
  const canvasRef = useRef<HTMLCanvasElement>(null), fileInput = useRef<HTMLInputElement>(null), total = pdf?.numPages || 12
  const percent = Math.round((page / total) * 100)
  const changePage = (value: number) => setPage(Math.min(total, Math.max(1, value)))

  useEffect(() => { let cancelled = false; if (!pdf || !canvasRef.current) return; pdf.getPage(page).then(async (loadedPage) => { if (cancelled) return; const canvas = canvasRef.current!; const scale = zoom / 100; const viewport = loadedPage.getViewport({ scale, rotation }); canvas.width = viewport.width; canvas.height = viewport.height; await loadedPage.render({ canvasContext: canvas.getContext("2d")!, canvas, viewport }).promise }); return () => { cancelled = true } }, [pdf, page, zoom, rotation])
  const handleFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setFilename(file.name); setPage(1); setPdf(await pdfjsLib.getDocument({ data: await file.arrayBuffer() }).promise) }
  const printDocument = () => window.print()
  const fullscreen = async () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen().catch(() => {})
  const share = async () => { if (navigator.share) await navigator.share({ title: filename || "PDF document" }).catch(() => {}) }

  return <main className={dark ? "reader-app dark-reader" : "reader-app"}>
    <input ref={fileInput} type="file" accept="application/pdf,.pdf" className="sr-only" onChange={handleFile} aria-label="Choose a PDF file" />
    <header className="topbar"><div className="brand"><BookOpen size={19} /><span>sumatra</span><b>web</b></div><nav className="file-nav" aria-label="Document menu"><button onClick={() => fileInput.current?.click()}><FolderOpen size={16} /> Open</button><button onClick={() => filename && alert(`Saved copy of ${filename}`)} disabled={!filename}><Download size={16} /> Save as</button><button onClick={printDocument}><Printer size={16} /> Print</button></nav><div className="top-actions"><button className="icon-button" onClick={() => setSearchOpen(!searchOpen)} aria-label="Search document"><Search size={17} /></button><button className="icon-button" onClick={() => setMobileMenu(!mobileMenu)} aria-label="More options"><MoreHorizontal size={18} /></button></div></header>
    <div className="toolbar"><button className="mobile-only icon-button" onClick={() => setSidebar(!sidebar)} aria-label="Toggle sidebar"><Menu size={18} /></button><div className="tool-group"><button className="tool-button" onClick={() => setSidebar(!sidebar)} aria-label="Toggle sidebar"><PanelLeft size={17} /></button><span className="divider" /><button className="tool-button" onClick={() => changePage(page - 1)} disabled={page === 1} aria-label="Previous page"><ChevronLeft size={18} /></button><div className="page-input"><input value={page} onChange={e => changePage(Number(e.target.value) || 1)} aria-label="Current page" /><span>/ {total}</span></div><button className="tool-button" onClick={() => changePage(page + 1)} disabled={page === total} aria-label="Next page"><ChevronRight size={18} /></button></div><div className="toolbar-title"><FileText size={15} /> <span>{filename || "Demo document"}</span></div><div className="tool-group right-tools"><button className="tool-button" onClick={() => setZoom(Math.max(50, zoom - 10))} aria-label="Zoom out"><Minus size={17} /></button><button className="zoom-value" onClick={() => setZoom(100)} aria-label="Reset zoom">{zoom}%</button><button className="tool-button" onClick={() => setZoom(Math.min(200, zoom + 10))} aria-label="Zoom in"><Plus size={17} /></button><span className="divider" /><button className="tool-button" onClick={() => setRotation((rotation + 90) % 360)} aria-label="Rotate page"><RotateCw size={16} /></button><button className="tool-button" onClick={fullscreen} aria-label="Fullscreen"><Fullscreen size={16} /></button></div></div>
    {searchOpen && <div className="searchbar"><Search size={16} /><input autoFocus placeholder="Search in document" aria-label="Search in document" /><span>{pdf ? "Search loaded PDF" : "Open a PDF to search"}</span><button onClick={() => setSearchOpen(false)} aria-label="Close search"><X size={16} /></button></div>}
    <div className="workspace">{sidebar && <aside className="sidebar"><div className="side-tabs"><button className={tab === "outline" ? "active" : ""} onClick={() => setTab("outline")}>Outline</button><button className={tab === "pages" ? "active" : ""} onClick={() => setTab("pages")}>Pages</button></div><div className="outline"><p className="eyebrow">{tab === "outline" ? "DOCUMENT OUTLINE" : "PAGE THUMBNAILS"}</p>{Array.from({ length: total }, (_, i) => <button key={i} className={page === i + 1 ? "outline-item active" : "outline-item"} onClick={() => changePage(i + 1)}><span>{tab === "outline" ? chapters[i] || `Page ${i + 1}` : `Page ${i + 1}`}</span><small>{i + 1}</small></button>)}</div><div className="side-footer"><button onClick={() => setDark(!dark)}><SlidersHorizontal size={15} /> {dark ? "Light mode" : "Dark mode"}</button></div></aside>}
      <section className="canvas" aria-label="Document reader"><div className="canvas-topline"><span>{filename ? "PDF DOCUMENT" : "DEMO DOCUMENT"}</span><span>{percent}% read</span></div>{pdf ? <div className="pdf-stage"><canvas ref={canvasRef} aria-label={`Page ${page} of ${total}`} /></div> : <article className="paper"><div className="paper-kicker">SUMATRA WEB / QUICK GUIDE</div><h1>{chapters[page - 1] || "Document page"}<br /><em>with SumatraPDF</em></h1><p className="lead">Open a PDF to start reading it here.</p><div className="cover-rule" /><div className="cover-meta"><span>PAGE {String(page).padStart(2, "0")}</span><span>2026 EDITION</span></div><div className="paper-stamp">PDF<br /><b>READER</b></div></article>}<div className="canvas-footer"><span>Page {page} of {total}</span><div className="progress"><i style={{ width: `${percent}%` }} /></div><span>{zoom}%</span></div></section></div>
    <footer className="statusbar"><span><span className="status-dot" /> {filename ? "PDF ready" : "Ready"}</span><span className="status-path">{filename || "No file open · Open a PDF to begin reading"}</span><span className="status-right">{rotation}° <Share2 size={13} onClick={share} /></span></footer>
    {mobileMenu && <div className="mobile-popover"><button onClick={share}><Share2 size={15} /> Share document</button><button onClick={() => fileInput.current?.click()}><FolderOpen size={15} /> Open PDF</button><button onClick={printDocument}><Printer size={15} /> Print</button></div>}
  </main>
}
